# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:16.1
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080